name: 'Jira ticket validator'
description: 'Verify that given fields exist on a Jira ticket'
author: 'invakid404'
inputs:
  ticket:
    required: false
    description: "Jira ticket to validate; action is a noop if not supplied"
  host:
    required: true
    description: "Hostname of Jira instance"
  username:
    required: true
    description: "Username to use for Jira"
  password:
    required: true
    description: "Password/token to use for Jira"
runs:
  using: 'node12'
  main: 'dist/index.js'
